version: '2'

services:
  php-apache:
    image: xfrocks/docker-xenforo:php-apache
    expose:
      - "80"
    links:
      - mysqld:mysqld
    volumes:
      - .:/var/www/html/

  php-cli:
    image: xfrocks/docker-xenforo:php-cli
    links:
      - php-apache:php-apache
      - mysqld:mysqld
    volumes_from:
      - php-apache
    working_dir: /var/www/html/

  mysqld:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ONETIME_PASSWORD: 'yes'
      MYSQL_DATABASE: 'xenforo'
      MYSQL_USER: 'xenforo'
      MYSQL_PASSWORD: 'xenforo'
    expose:
      - "3306"
    volumes:
      - ./internal_data/mysql:/var/lib/mysql:rw

  mysql:
    image: arey/mysql-client
    links:
      - mysqld:mysqld
    volumes_from:
      - php-apache
    working_dir: /var/www/html/
    entrypoint: mysql -hmysqld -uxenforo -pxenforo xenforo