name: Container Build and Publish

on:
  push:
    branch: "master"
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install digital ocean cli tool
        # You may pin to the exact commit or the version.
        # uses: digitalocean/action-doctl@135ac0aa0eed4437d547c6f12c364d3006b42824
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_REGISTRY_ACCESS_TOKEN }}

      - name: Build php-fpm container image
        run: docker build ./php-fpm -t ${{ vars.CONTAINER_REGISTRY_NAME }}/php-fpm:$(echo $GITHUB_SHA | head -c7)

      - name: Build nginx container image
        run: docker build ./nginx -t ${{ vars.CONTAINER_REGISTRY_NAME }}/nginx:$(echo $GITHUB_SHA | head -c7)

      - name: Log in to digital ocean container registry for push
        run: doctl registry login --expiry-seconds 1200

      - name: Push php-fpm image
        run: docker push ${{ vars.CONTAINER_REGISTRY_NAME }}/php-fpm:$(echo $GITHUB_SHA | head -c7)

      - name: Push nginx image
        run: docker push ${{ vars.CONTAINER_REGISTRY_NAME }}/nginx:$(echo $GITHUB_SHA | head -c7)
